### ISSUE TITLE
Scroll position not restored

### ISSUE THREAD

**Issue by kurtextrem** [studioddtonline/Silverbird-M#10]
In the latest changes from the "develop" branch, the scroll position isn't stored anymore (which means whenever you open the popup, it starts at the top)

**Comment by studioddtonline** [comment]
It is a removed feature since 0.5.6.15
https://github.com/studioddtonline/Silverbird-M/commit/0ab900e5a5dce977ba67eb8155f605a7cb75da19

**Comment by kurtextrem** [comment]
Thank you. Why so?

**Comment by studioddtonline** [comment]
TBH, the reason I do not remember.
Something... to reduce the dependency on jQuery...

**Comment by kurtextrem** [comment]
Don't you think it is an useful feature?

If you want I could look into re-implementing it (without jQuery if desired).

**Comment by kurtextrem** [comment]
@studioddtonline I've seen the experimental version yesterday and it works great. Thanks a lot!
