### ISSUE TITLE
Tooltip: When expanding URL, it should automatically show the result

### ISSUE THREAD

**Issue by kurtextrem** [studioddtonline/Silverbird-M#13]
When I hover an image or shortened URL, thiss tooltip shows up: http://prntscr.com/eu939q

Expected:
It shows "URL expanding..." and after it has done the XHR, it shows the result

How it is:
It shows "URL expanding..." and stays like that even after the XHR has finished. When I hover over the link again, it shows the result

**Comment by studioddtonline** [comment]
I think so, too.
For now, it was improved a content preloading, because it is troublesome that tooltip makes to be a content replaceable.

**Comment by kurtextrem** [comment]
Seems to be fixed
