### ISSUE TITLE
can you make height of popup extendable?

### ISSUE THREAD

**Issue by fredzannarbor** [studioddtonline/Silverbird-M#18]
I would like to be able to drag the popup down so it it is taller.

**Comment by kurtextrem** [comment]
This is possible already, hover where the arrow is: http://prntscr.com/h1kj8d

**Comment by fredzannarbor** [comment]
That makes the tweet expand. I mean the entire pane that contains all the tweets.  It can expand to the right and left but not to the bottom, at least on my Mac/Chrome.

**Comment by kurtextrem** [comment]
It expands for me, hm. Maybe because of my fork? Not sure.

**Comment by fredzannarbor** [comment]
I see how it's meant to work with the popout triangle.  what I wanted to do was to extend the pulldown "blinds" but that's not necessary with the popout.
