### ISSUE TITLE
from: -"searchphrase" search doesn't work properly in search box

### ISSUE THREAD

**Issue by fredzannarbor** [studioddtonline/Silverbird-M#23]
from:big_cases -"Doc. on Pacer" does not exclude tweets containing "Doc. on Pacer", whereas the same search from the Twitter homepage does.

https://twitter.com/search?q=from%3Abig_cases%20-"Doc.%20on%20Pacer"&src=typd

**Comment by studioddtonline** [comment]
`from:USERNAME` is a special keyword of Silverbird M.
try this workaround:
-"Doc. on Pacer" from:big_cases

**Comment by fredzannarbor** [comment]
thanks!
